--[[
	Korean Locale.
]]

local L = LibStub("AceLocale-3.0"):NewLocale("WhoTaunted", "koKR", true);
if not L then return end

L["<WhoTaunted>"] = true
L["against"] = ":"
L["Announcements"] = "알림"
L["Anounce AOE Taunts"] = "광역 도발 알리기"
L["Anounce AOE Taunts Output:"] = "광역 도발 알림 출력:"
L["Anounce AOE Taunts."] = "광역 도발을 알립니다."
L["Anounce Fails"] = "실패 알리기"
L["Anounce Fails Output:"] = "실패 알림 출력:"
L["Anounce Taunts"] = "도발 알리기"
L["Anounce Taunts Output:"] = "도발 알림 출력:"
L["Anounce taunts that fail."] = "도발 실패를 알립니다."
L["Anounce taunts."] = "도발을 알립니다."
L["AOE"] = "광역"
L["AOE taunted using"] = "광역 도발 사용"
L["Chat Window"] = "대화창"
L["Disable Who Taunted?"] = "Who Taunted? 사용 안함"
L["Disable Who Taunted? in Battlegrounds"] = "전장에서 Who Taunted? 비활성"
L["Disable Who Taunted? in PvP Zones"] = "PvP 지역에서 Who Taunted? 비활성"
L["Disables Who Taunted? while you are in a battleground."] = "전장에서 Who Taunted? 비활성 합니다."
L["Disables Who Taunted? while you are in PvP Zones such as Ashran."] = "아쉬란 같은 PvP 지역에서 Who Taunted?를 비활성 합니다."
L["Disables Who Taunted?."] = "Who Taunted?를 비활성합니다."
L["Display Ability"] = "능력 표시"
L["Display the ability that was used to taunt."] = "도발에 사용한 능력을 표시합니다."
L["Don't show your own failed taunts."] = "자신이 실패한 도발은 표시하지 않습니다."
L["Don't show your own taunts."] = "자신이 사용한 도발은 표시하지 않습니다."
L["etc"] = "기타"
L["Failed:"] = "실패:"
L["General"] = "일반"
L["Hide Own Failed Taunts"] = "자신의 실패한 도발 숨기기"
L["Hide Own Taunts"] = "자신의 도발 숨기기"
L["Immune"] = "면역"
L["Include Prefix"] = "접두사 포함"
L["Include the"] = "포함"
L["Party"] = "파티"
L["prefix when a message's output is"] = "출력 메시지에 접두사 표시"
L["Raid"] = "공격대"
L["Raid Warning"] = "공격대 경보"
L["'s"] = "의"
L["Say"] = "일반"
L["Self"] = "혼자보기"
L["Show"] = "보이기"
L["Target"] = "대상"
L["taunt"] = "도발"
L["taunted"] = "도발"
L["taunts"] = "도발"
L["The chat window taunts will be announced in when the output is set to"] = "도발 알림 메시지를 출력할 대화창 설정"
L["using"] = "사용"
L["Where AOE Taunts will be announced."] = "광역 도발 사용을 알릴 곳."
L["Where taunts will be announced."] = "도발 사용을 알릴 곳."
L["Where the taunt fails will be announced."] = "도발 실패를 알릴 곳."
L["Who Taunted?"] = true
L["Yell"] = "외치기"

