local CL_FontUrl = "Interface\\AddOns\\ConsLegion\\Font\\"
local CL_Font = CL_FontUrl.."LiberationSans-Regular.TTF"
local CL_Version = tonumber(GetAddOnMetadata("ConsLegion", "Version"))
ConsLegion.CL_panel = CreateFrame( "Frame", "CLPanelFrame", UIParent)
ConsLegion.CL_panel.name = "ConsLegion"
InterfaceOptions_AddCategory(ConsLegion.CL_panel)
CL_panel = {}
CL_panel.title = CreateFrame("SimpleHTML",nil,ConsLegion.CL_panel)
CL_panel.title:SetWidth(500)
CL_panel.title:SetHeight(20)
CL_panel.title:SetPoint("TOPLEFT", ConsLegion.CL_panel, 100,-30)
CL_panel.title:SetFont(CL_Font, 18,"OUTLINE")
CL_panel.title:SetText("ConsLegion v" .. CL_Version)
CL_panel.Button1 = CreateFrame("Button", "ZPButton2", ConsLegion.CL_panel)
CL_panel.Button1:SetPoint("TOPLEFT", ConsLegion.CL_panel, "TOPLEFT", 120, -100)
CL_panel.Button1:SetWidth(70)
CL_panel.Button1:SetHeight(30)
CL_panel.Button1:SetText("Load")
CL_panel.Button1:SetNormalFontObject("GameFontNormal")
CL_panel.Button1ntex = CL_panel.Button1:CreateTexture()
CL_panel.Button1ntex:SetTexture("Interface/Buttons/UI-Panel-Button-Up")
CL_panel.Button1ntex:SetTexCoord(0, 0.625, 0, 0.6875)
CL_panel.Button1ntex:SetAllPoints()	
CL_panel.Button1:SetNormalTexture(CL_panel.Button1ntex)
CL_panel.Button1htex = CL_panel.Button1:CreateTexture()
CL_panel.Button1htex:SetTexture("Interface/Buttons/UI-Panel-Button-Highlight")
CL_panel.Button1htex:SetTexCoord(0, 0.625, 0, 0.6875)
CL_panel.Button1htex:SetAllPoints()
CL_panel.Button1:SetHighlightTexture(CL_panel.Button1htex)
CL_panel.Button1ptex = CL_panel.Button1:CreateTexture()
CL_panel.Button1ptex:SetTexture("Interface/Buttons/UI-Panel-Button-Down")
CL_panel.Button1ptex:SetTexCoord(0, 0.625, 0, 0.6875)
CL_panel.Button1ptex:SetAllPoints()
CL_panel.Button1:SetPushedTexture(CL_panel.Button1ptex)
CL_panel.Button1:SetScript("OnClick", function(self, arg1)
	CL_Settings()
end)