local LSM = LibStub("LibSharedMedia-3.0")

if LSM == nil then return end

--LSM:Register("font","BEISPIEL", [[Interface\AddOns\ElvUI_MaUI\media\fonts\BEISPIEL.ttf]])
LSM:Register("statusbar","MaUI 1", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI1.tga]])
LSM:Register("statusbar","MaUI 2", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI2.tga]])
LSM:Register("statusbar","MaUI 3", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI3.tga]])
LSM:Register("statusbar","MaUI 4", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI4.tga]])
LSM:Register("statusbar","MaUI 5", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI5.tga]])
LSM:Register("statusbar","MaUI 6", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI6.tga]])
LSM:Register("statusbar","MaUI 7", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI7.tga]])
LSM:Register("statusbar","MaUI 8", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI8.tga]])
LSM:Register("statusbar","MaUI 9", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI9.tga]])
LSM:Register("statusbar","MaUI 10", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI10.tga]])
LSM:Register("statusbar","MaUI 11", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI11.tga]])
LSM:Register("statusbar","MaUI 12", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI12.tga]])
LSM:Register("statusbar","MaUI 13", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI13.tga]])
LSM:Register("statusbar","MaUI 14", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI14.tga]])
LSM:Register("statusbar","MaUI 15", [[Interface\AddOns\ElvUI_mMediaTag\media\textures\MaUI15.tga]])
