--[[
	German Locale.
]]

local L = LibStub("AceLocale-3.0"):NewLocale("WhoTaunted", "deDE", true);
if not L then return end

L["<WhoTaunted>"] = "<Wer pullte>"
L["against"] = "gegen"
L["Announcements"] = "Ankündigungen"
L["Anounce AOE Taunts"] = "Berichte AOE Spots"
L["Anounce AOE Taunts Output:"] = "Poste AOE Spot nach:"
L["Anounce AOE Taunts."] = "Berichte AOE Spots"
L["Anounce Fails"] = "Fehlgeschlagenes anzeigen"
L["Anounce Fails Output:"] = "Ansagenausgabe:"
L["Anounce Taunts"] = "Berichte wer spottete"
L["Anounce Taunts Output:"] = "Ausgabe \"Wer spottete\" nach:"
L["Anounce taunts that fail."] = "Fehlgeschlagene Spotts anzeigen"
L["Anounce taunts."] = "Berichte wer spottete"
L["AOE"] = "Flächenschaden"
L["AOE taunted using"] = "Flächenspottnutzung"
L["Chat Window"] = "Chat Fenster"
L["Disable Who Taunted?"] = "Who Taunted? deaktivieren"
L["Disable Who Taunted? in Battlegrounds"] = "Who Taunted? in Schlachtfelder deaktivieren"
L["Disable Who Taunted? in PvP Zones"] = "Who Taunted? in PvP-Gebieten deaktivieren"
L["Disables Who Taunted? while you are in a battleground."] = "Deaktiviert Who Taunted? während du dich in Schlachtfeldern befindest."
L["Disables Who Taunted? while you are in PvP Zones such as Ashran."] = "Deaktiviert Who Taunted?, während du dich einer PvP-Zone wie z.b. Ashran befindest."
L["Disables Who Taunted?."] = "Deaktiviert Who Taunted?."
L["Display Ability"] = "Möglichleit ausschalten"
L["Display the ability that was used to taunt."] = "Zeige an, womit gepullt wurde"
L["Don't show your own failed taunts."] = "Zeige eigene fehlgeschlagene Pulls nicht"
L["Don't show your own taunts."] = "Zeige eigene Pulls nicht."
L["etc"] = "etc."
L["Failed:"] = "Fehlgeschlagen:"
L["General"] = "Hauptsächlich."
L["Hide Own Failed Taunts"] = "Verstecke eigene fehlgeschlagene Spots."
L["Hide Own Taunts"] = "Verstecke eigene Spots"
L["Immune"] = "Immun"
L["Include Prefix"] = "mit Präfix"
L["Include the"] = "Mit"
L["Party"] = "Gruppe"
L["prefix when a message's output is"] = "Präfix wenn "
L["Raid"] = "Schlachtzug"
L["Raid Warning"] = "Schlachtzugswarnung"
L["'s"] = true
L["Say"] = "Sagen"
L["Self"] = "Eigener Chat"
L["Show"] = "Zeige"
L["Target"] = "Ziel"
L["taunt"] = "Spot"
L["taunted"] = "Gespottet"
L["taunts"] = "spottet"
L["The chat window taunts will be announced in when the output is set to"] = "Die Chat Spotts werden in angezeigt, wenn die Ausgabe auf gestellt ist."
L["using"] = "verwendet"
L["Where AOE Taunts will be announced."] = "Wohin sollen Pulls gepostet werden"
L["Where taunts will be announced."] = "Wo sollen Spots ausgegeben werden ?"
L["Where the taunt fails will be announced."] = "Wo die fehlgeschlagenen Spotts angezeigt werden."
L["Who Taunted?"] = "Wer spottete ?"
L["Yell"] = "Schreien"

